version: '3'

services:
  gateway:
    container_name: gateway
    restart: always
    build: ./gateway
    ports:

      - "3004:3004"
  characters:
    container_name: characters
    restart: always
    build: ./characters
    ports:

      - "3001:3001"
  films:
    container_name: films
    restart: always
    build: ./films
    ports:

      - "3002:3002"
  planets:
    container_name: planets
    restart: always
    build: ./planets
    ports:

      - "3003:3003"
  microservicesdb:
    container_name: microservicesdb
    restart: always
    build: ./database
    ports:

      - "3005:3005"
    env_file:
      - ./database/.env